[IoModule1]
IP = 127.0.0.1
PORT = 502

[IoModule2]
IP = 127.0.0.1
PORT = 502

[UpperBarcodeReader]
IP = 127.0.0.
PORT = 1

[LowerBarcodeReader]
IP = 127.0.0.1
PORT = 2

[LaserDisplacementSensor]
TYPE = DLEN1
PORT = 64000

[Production]
Pqty = 23
RecipeName = Test
IsZeroSetOk = True
Delay_BoardStopAck = 1000
Timeout_WaitStopper = 5000
Timeout_WaitInPlace = 10000
Timeout_WaitExit = 10000
Timeout_OnEntry = 5000
Timeout_OnExit = 5000
Timeout_MeasuThickness = 3000
Timeout_ReadBarcode = 5000
Timeout_SendBsk = 10000

[Path]
InsertType = A
BskDir = \BSK
XmlDir = D:\Software\XmlTest
LockState = \Log\Error\LockState.json
SqLiteFile = \Database\ASE_A3_SBC-2D.db

[User]
Operaor = 0
Engineer = 1
Vendor = 2

[LockMachine]
ConsecutiveError_Max = 3
ConsecutiveError_IntervalTime = 1
CumulativeError_Max = 3
CumulativeError_IntervalTime = 1

[Engineer]
Pw = ASE

[Vendor]
Pw = 09490128
